name: PjB
favicon: null
layout_spectrum: 0.7288701527286321
typography_spectrum: 0.8232950656674802
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1441860452760011
  lightness: 0.8361377667170018
  saturation: 0.7508467305451632
  rhythmicContrast: 0.3184381148312241
purpose: []
