analytics: {}
color:
  brandColors:
    - '#b4b85e'
    - '#d46231'
    - '#542132'
    - '#74d7e6'
    - '#775de9'
  brandStrength: 0.6875
  lightness: 0.836137
  rhythmicContrast: 0.640625
  saturation: 0.375
cta: {}
layout_spectrum: 0.379112
name: PjB
opengraph: {}
purpose: []
typography_spectrum: 0.588816
