name: PjB
favicon: null
layout_spectrum: 0.59698
typography_spectrum: 0.86563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b4b85e'
    - '#d46231'
    - '#542132'
    - '#74d7e6'
    - '#775de9'
  brandStrength: 0.6875
  lightness: 0.8361377667170018
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
